# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24c954f4b8808f574383c4fb86cf4f1ae412b3fb1eb384c90a4e3d4048fe46679e08566cfa574018a81230d8492366851d1253b2eb14ab0c45050e824f3559c0

test:
  secret_key_base: 0b10455394f5c015d8d7add7226f2b03249a223d1b10f8a8f4be6df08ee9a90188e3c2f3865ac29310e98a0d2718159ea0f48ec68fdcf856b188012e370df0cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
